export const SITE_NAME: string = 'Sachin — Dev Blog'
export const SITE_TEMPLATE: string = '%s — Sachin'
export const SITE_DESCRIPTION: string = 'Engineering notes, systems, and real-world code.'
export const RSS_URL: string = '/rss.xml'
export const NEW_POST_THRESHOLD_DAYS: number = 14
export const COPY_TIMEOUT: number = 1200
export const SITE_HEADER: string = 'Writing'
export const SITE_INTRO: string = 'Notes on software engineering, systems, and things I learn while building.'
export const DATE_FORMAT: string = 'MMMM d, yyyy'
export const SITE_URL: string = process.env.NEXT_PUBLIC_SITE_URL || 'https://blog.sachinpasi.com'
export const AUTHOR_NAME: string = 'Sachin Pasi'
export const DEFAULT_THEME: string = 'dark'